[env:teensy41]
platform  = teensy
board     = teensy41
framework = arduino

; Bibliothèque HX711 de bogde (compatible Teensy, SCK commun)
lib_deps  = bogde/HX711@^0.7.5

; Vitesse upload
upload_speed = 115200

; Moniteur série — avec saisie activée
monitor_speed  = 115200
monitor_echo   = yes
monitor_eol    = LF