[env:seeed_wio_terminal]
platform = atmelsam
board = seeed_wio_terminal
framework = arduino

lib_deps =
    bogde/HX711
    seeed-studio/Seeed Arduino rpcWiFi
    seeed-studio/Seeed Arduino FS
    seeed-studio/Seeed Arduino SFUD
    seeed-studio/Seeed Arduino rpcUnified
    seeed-studio/Seeed_Arduino_mbedtls
    seeed-studio/Seeed Arduino rpcBLE
    https://github.com/Seeed-Studio/Seeed_Arduino_LCD.git

monitor_speed = 115200
